name = "TrixiShallowWater"
uuid = "804cb1fc-5b08-4398-a671-a789bfe091b3"
authors = ["Andrew R. Winters <andrew.ross.winters@liu.se>", "Michael Schlottke-Lakemper <michael@sloede.com>"]
version = "0.2.3-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MuladdMacro = "46d2c3a1-f734-5fdb-9937-b9b9aeba4221"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
Static = "aedffcd0-7271-4cad-89d0-dc628f76c6d3"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Trixi = "a7f1ee26-1774-49b1-8366-f1abc58fbfcb"

[compat]
LinearAlgebra = "1"
MuladdMacro = "0.2.4"
Printf = "1"
Roots = "2.1.6"
Static = "1.1.1"
StaticArrays = "1.9"
Trixi = "0.13"
julia = "1.10"
